apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myblogs
spec:
  selector:
    matchLabels:
      app: myblogs
  template:
    metadata:
      labels:
        app: myblogs
    spec:
      containers:
      - name: myblogs
        image: registry.gitlab.com/ittipatlk/myblogs/sample:latest
        ports:
        - containerPort: 8003
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: myblogs
spec:
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
  selector:
    app: myblogs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myblogs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myblogs
            port:
              number: 8003
