apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: registry.gitlab.com/ittipatlk/blog/sample:latest
        ports:
        - containerPort: 8002
        env:
        - name: APP_HOST
          value: "localhost"
        - name: BLOG_PORT
          value: "8002"
        - name: CORS_ALLOW_HEADERS
          value: "Content-Type,Authorization"
        - name: CORS_ALLOW_METHODS
          value: "GET,POST,PUT,DELETE,OPTIONS"
        - name: CORS_ALLOW_ORIGINS
          value: "*"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME_BLOG
          value: "postgres"
        - name: DB_PASSWORD_BLOG
          value: "27926"
        - name: DB_DATABASE_BLOG
          value: "myblogs"
        - name: DB_SCHEMA_BLOG
          value: "myblogs"
        - name: DB_SSLMOD
          value: "disable"
        - name: KAFKA_CLIENT_ID
          value: "blog"
        - name: KAFKA_GROUP_ID
          value: "myblogs"
        - name: KAFKA_SERVERS
          value: "kafka"
        - name: KAFKA_PORT
          value: "9092"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    app: blog
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /v1/myblogs/getBlogs
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 8002
      - path: /v1/myblogs/createBlog
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 8002